#!/bin/bash
#----------------------------------------------------------
# Syno_Toolbox has no persistent background daemon, but several
# modules need to run once at package start (trigger: "boot" or
# "scheduled" in modules.json, when enabled) - e.g. DSM Telnet
# Password, Sequential I/O Tuning, Uninstall Active Insight.
#----------------------------------------------------------

PKG_ROOT="/var/packages/Syno_Toolbox"
DSM=$(/usr/syno/bin/synogetkeyvalue /etc.defaults/VERSION majorversion)
if [[ $DSM -ge 7 ]]; then
    VAR_DIR="${PKG_ROOT}/var"
else
    VAR_DIR="${PKG_ROOT}/etc"
fi

case "$1" in
    start)
        "${PKG_ROOT}/target/bin/run_boot_modules.sh" >> "${VAR_DIR}/synotoolbox.log" 2>&1
        exit 0
        ;;
    stop)
        exit 0
        ;;
    status)
        exit 0
        ;;
    log)
        exit 0
        ;;
    *)
        exit 1
        ;;
esac
